import Head from "next/head";
import Link from "next/link";
import { NAV_ITEMS } from "../data";
import Intro from "./components/Intro";
import Tech from "./components/Tech";
import Trouble from "./components/Trouble";
import Diagram from "./components/Diagram";

export default function Home() {
  return (
    <div className="portfolioPost">
      <Head>
        <title>Portfolio | PortForU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="postHeader">
        <h1 className="postTitle">포트폴리오 | PortForU</h1>
      </header>

      <main className="postContent">
        <img
          src="https://github.com/user-attachments/assets/919b7463-f245-4bd4-89cc-6101848486fe"
          alt="Thumbnail"
          className="mainImage"
        />

        <nav className="tableOfContents">
          <h3>Contents</h3>
          <ul>
            {NAV_ITEMS.map((item) => (
              <li key={item.id}>
                <Link href={`#${item.id}`}>
                  {item.title}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        <Intro />
        <hr />
        <Tech />
        <hr />
        <Trouble />
        <hr />
        <Diagram />
      </main>
    </div>
  );
}